### ISSUE TITLE
Exception when importing lib

### ISSUE THREAD

**Issue by HuiiBuh** [HTMLElements/smart-webcomponents#24]
Importing the lib causes an exception. This is the case for the last few version.
I am really frustrated with this lib. You have breaking changes in minor versions, poorly typed events and really bad performance because you run change detection on mouse move, which you should NEVER do!
I don't know why my company spent quite a lot of money on this and I would expect a better product for this price.

"smart-webcomponents-angular": "^13.0.30"
Chrome Version 99.0.4844.82 (Official Build) (64-bit)
Linux 

```
TypeError: s.startsWith is not a function
    at _.defineElementMethods (smart.ganttchart.js:62:72606)
    at _.defineElement (smart.ganttchart.js:62:68085)
    at Function.register (smart.ganttchart.js:62:76708)
    at window.<computed> (smart.ganttchart.js:62:83605)
    at smart.ganttchart.js:62:93646
    at Object.6321 (smart.ganttchart.js:62:2)
    at __nested_webpack_require_2095860__ (smart.ganttchart.js:205:12)
    at smart.ganttchart.js:247:75
    at smart.ganttchart.js:244:1
    at Object.6626 (smart.ganttchart.js:7:10)
    at __webpack_require__ (bootstrap:19:1)
    at Module.71476 (mapOneOrManyArgs.js:8:1)
    at __webpack_require__ (bootstrap:19:1)
    at Module.66346 (temporal-view.module.ts:33:34)
    at __webpack_require__ (bootstrap:19:1)
```

**Comment by bmarkov** [comment]
Hi, in the recent version we did not introduce any changes about the Gantt Chart. We will review the reported exception and will resolve it, when we replicate it. Thank you for the feedback!

**Comment by HuiiBuh** [comment]
We only use the Gantt chart part....

For the types:
+ datasource has the type any
+ Every event has the type CustomEvent without an generic argument, therefore the event detail, most likely the only relevant data has the type any

Performance:
+ You listen for fast firing events  (mouse move, etc...) in the ngZone which leads to lots of change detection cycles through the whole app.

General:
+ Gantt Resize event proxies the SMART-SPLITTER resize event which is not relevant any you have to filter for the gantt resize

**Comment by bmarkov** [comment]
1. All events are described in the documentation. The Type is CustomEvent(https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) because we fire custom events. The arguments and event details are different and documented in the docs pages.
2.Yes, we do listen to mouse events and we perform multiple actions on mouse events. We also handle pointer and touch events in our library and all UI libraries do the same. For example, if you want to resize something, you have 3 actions, click, move and release the pointer. However, in the mouse/pointer/touch events we check whether we should or should not handle it for the purposes of the component and we do listen to elements relevant to the HTML Element itself not global events. If you have any specific case where you think we should not do that, please share that information and we will review the specific use-case in our code base.
3. Events in Web Applications bubble up. Yes, the Splitter has 'resize' event and if you listen to Gantt's resize and you resize the splitter inside the Gantt, you will get the event. Similar cases are the focus, click, mousedown, mouseup events.

**Comment by HuiiBuh** [comment]
1. I know that the arguments are different. But CustomEvent has a generic type, so you could type them and if they vary use type unions, so the user can write some typeguards.
2. It is just that fast firing events should not be listened to in the ngZone, because they trigger change detection
3. I think this is more up to preference, but in most angular libraries custom events do not bubble up like native browser events and I would expect an angular library to behave more like an angular lib. But because you use custom elements underneath I would think that you are somewhat limited in your options in that regard...
4. In this case you could perhaps provide the different types as type union, just as a way to improve usability. In my opinion you should not have to go into the documentation just to lookup the data-structure of something. This is the advantage of typed languages...

And I am sorry when my first message was a bit harsh. I just had a really bad time with the lib and was somewhat frustrated, but this is not really an excuse to write something like this...
